### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by lincruste** [Rinnegatamante/vitaHexenII#1]
Hi,
The settings are not saved from one session to another. Crosshair, inverted cam, always run, etc have to be set back every time.

Thank you very much for your dedication in porting those MS-DOS/Win 9x games on PS Vita.

**Comment by Rinnegatamante** [comment]
Does the problem happen if you close the game with the Exit option?

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/vitaHexenII/commit/d24c33e141157164434b9be63aed0d1916ec79ea
