### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/vitaHexenII#3]
I cannot get the music to work. I am using the latest version 1.1. 

I tried ogg and mp3. I tried Casa1.ogg style filenames and track02.ogg style. I even re-encoded the files and converted them myself between ogg and mp3. Nothing worked.

I noticed I get a loud, short "static" sound when booting up the game. Maybe that is the music player thread crashing? Everything else works perfect, just no music.

**Comment by Rinnegatamante** [comment]
If a music thread crashes, the whole app will crash with a coredump.
Where are you placing cdaudio tracks?

**Comment by rsn8887** [comment]
I put them in ux0:/data/Hexen II/cdtracks/ . I tried ogg, mp3 and both naming schemes. I thought maybe my music files were bad, but I converted them to mp3 and back to ogg using audacity.

**Comment by Rinnegatamante** [comment]
Looks correct to me. I'm sure it worked with the audiofiles i have. I can try to send them to you if i still have them on my Vita (have to check).

**Comment by rsn8887** [comment]
That would be awesome! If you have it, can you upload it on Mega or email an example, e.g. the song that plays in level 1, to me, raist66676 “at” gmx.de ? Thanks!

**Comment by Rinnegatamante** [comment]
http://rinnegatamante.it/cdtracks.rar

**Comment by rsn8887** [comment]
I used your exact files, copied them to ux0:data/Hexen II/cdtracks , but still no music. I have now tried mp3, ogg, and your midi files. The version I am using is v1.1 from vita DB (is there a newer version?).

When I start the game, I get a short burst of static. During the demo and game,  there are only sound effects, no music. I verified that music volume is cranked up in the menu.

Maybe my pak0 etc files are wrong? But everything plays perfect. Just no music.

**Comment by Rinnegatamante** [comment]
No there isn't a new version. I might double check if the version  on VitaDB is running with latest eboot file.

**Comment by rsn8887** [comment]
I checked the Vitadb version I am using against the .vpk in this .rar file:
http://rinnegatamante.it/vitaHexenII_11.rar

and they were both identical. So it seems like I am using the latest version. Will test another version of the .wads to make sure it is not a problem with the .wad files.

**Comment by rsn8887** [comment]
I got the music to play. I replaced all my hexen game files with the ones from an official Hexen CD and now it works, at least with the .mid music files supplied by Rinnegatamante. So it must have been my Hexen files (.pak etc).
