### ISSUE TITLE
Ogg and mp3 cd tracks not loading

### ISSUE THREAD

**Issue by mrdude2478** [Rinnegatamante/vitaHexenII#6]
Currently renaming a mp3 or ogg file in cd tracks to mid file extension allows music to play. I believe this is a fault in the code of source/audiodec/cd_psp.cpp.

If I change line 234 to:
sprintf(tmp,"%s.ogg",fname);

instead of:

sprintf(tmp,"%s.mid",fname);

Then ogg cd tracks play properly with the correct ogg file extension, without needing to rename to mid.

**Comment by Rinnegatamante** [comment]
Didn't test but this should fix the issue: https://github.com/Rinnegatamante/vitaHexenII/commit/35be83c3bd3df1ab2053d3013537cc87225a4cd8

**Comment by mrdude2478** [comment]
Thanks, that working great now.
